import { Component } from '@angular/core';

@Component({
  selector: 'app-who-is-it',
  templateUrl: './who-is-it.component.html',
  styleUrls: ['./who-is-it.component.scss']
})
export class WhoIsITComponent {  
   persons = [
    {
      img: "./assets/public/exercise-3/001-man.svg",
      name:"juan",
      gender: "Man",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Red",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/002-man.svg",
      name:"Luis",
      gender: "Man",
      hairColor: "Blonde",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Orange",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/003-man.svg",
      name:"Jose",
      gender: "Man",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Green",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/004-man.svg",
      name:"Alberto",
      gender: "Man",
      hairColor: "Blonde",
      moustache: "No",
      glasses: "No",
      hatOrCap: "Yes",
      clothesColor: "Red",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/005-man.svg",
      name:"Raul",
      gender: "Man",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "White",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/006-man.svg",
      name:"Jesus",
      gender: "Man",
      hairColor: "Brown",
      moustache: "Yes",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Green",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/007-man.svg",
      name:"Miguel",
      gender: "Man",
      hairColor: "Red",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Black",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/008-man.svg",
      name:"John",
      gender: "Man",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "White",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/009-man.svg",
      name:"Brandon",
      gender: "Man",
      hairColor: "Blonde",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Orange",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/010-woman.svg",
      name:"Luisa",
      gender: "Woman",
      hairColor: "Brown",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Pink",
      skinColor: "Light",
      longHair: "Yes",
    },
    {
      img: "./assets/public/exercise-3/011-woman.svg",
      name:"Maria",
      gender: "Woman",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Orange",
      skinColor: "Light",
      longHair: "Yes",
    },
    {
      img: "./assets/public/exercise-3/012-woman.svg",
      name:"Flor",
      gender: "Woman",
      hairColor: "Red",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Black",
      skinColor: "Light",
      longHair: "Yes",
    },
    {
      img: "./assets/public/exercise-3/013-woman.svg",
      name:"Paula",
      gender: "Woman",
      hairColor: "White",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Pink",
      skinColor: "Light",
      longHair: "Yes",
    },
    {
      img: "./assets/public/exercise-3/014-woman.svg",
      name:"Sofia",
      gender: "Woman",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "White",
      skinColor: "Light",
      longHair: "Yes",
    },
    {
      img: "./assets/public/exercise-3/015-woman.svg",
      name:"Carmen",
      gender: "Woman",
      hairColor: "Brown",
      moustache: "No",
      glasses: "Yes",
      hatOrCap: "No",
      clothesColor: "Orange",
      skinColor: "Light",
      longHair: "Yes",
    },
    {
      img: "./assets/public/exercise-3/016-woman.svg",
      name:"Astrid",
      gender: "Woman",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "Yes",
      clothesColor: "Pink",
      skinColor: "Light",
      longHair: "Yes",
    },
    {
      img: "./assets/public/exercise-3/017-woman.svg",
      name:"Ana",
      gender: "Woman",
      hairColor: "Blonde",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Black",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/018-man.svg",
      name:"Cesar",
      gender: "Man",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "White",
      skinColor: "Dark",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/019-man.svg",
      name:"Armando",
      gender: "Man",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Red",
      skinColor: "Dark",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/020-man.svg",
      name:"Hugo",
      gender: "Man",
      hairColor: "Blonde",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Black",
      skinColor: "Dark",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/021-man.svg",
      name:"Steven",
      gender: "Man",
      hairColor: "Black",
      moustache: "Yes",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Orange",
      skinColor: "Dark",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/022-man.svg",
      name:"Arturo",
      gender: "Man",
      hairColor: "Black",
      moustache: "No",
      glasses: "Yes",
      hatOrCap: "No",
      clothesColor: "Black",
      skinColor: "Dark",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/023-man.svg",
      name:"Luigi",
      gender: "Man",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Orange",
      skinColor: "Dark",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/024-man.svg",
      name:"Carlos",
      gender: "Man",
      hairColor: "Blonde",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Black",
      skinColor: "Dark",
      longHair: "Yes",
    },
    {
      img: "./assets/public/exercise-3/025-man.svg",
      name:"Alejandro",
      gender: "Man",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Red",
      skinColor: "Dark",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/026-man.svg",
      name:"German",
      gender: "Man",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Red",
      skinColor: "Dark",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/027-woman.svg",
      name:"Indra",
      gender: "Woman",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Orange",
      skinColor: "Dark",
      longHair: "Yes",
    },
    {
      img: "./assets/public/exercise-3/028-woman.svg",
      name:"Carla",
      gender: "Woman",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Pink",
      skinColor: "Dark",
      longHair: "Yes",
    },
    {
      img: "./assets/public/exercise-3/029-woman.svg",
      name:"Estrella",
      gender: "Woman",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "White",
      skinColor: "Dark",
      longHair: "Yes",
    },
    {
      img: "./assets/public/exercise-3/030-woman.svg",
      name:"Lucero",
      gender: "Woman",
      hairColor: "Blonde",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Orange",
      skinColor: "Dark",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/031-woman.svg",
      name:"Esmeralda",
      gender: "Woman",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Green",
      skinColor: "Dark",
      longHair: "Yes",
    },
    {
      img: "./assets/public/exercise-3/032-woman.svg",
      name:"Rosa",
      gender: "Woman",
      hairColor: "Black",
      moustache: "No",
      glasses: "Yes",
      hatOrCap: "No",
      clothesColor: "Pink",
      skinColor: "Dark",
      longHair: "Yes",
    },
    {
      img: "./assets/public/exercise-3/033-woman.svg",
      name:"Zita",
      gender: "Woman",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Black",
      skinColor: "Dark",
      longHair: "Yes",
    },
    {
      img: "./assets/public/exercise-3/034-woman.svg",
      name:"Laura",
      gender: "Woman",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Pink",
      skinColor: "Dark",
      longHair: "Yes",
    },
    {
      img: "./assets/public/exercise-3/035-man.svg",
      name:"Mateo",
      gender: "Man",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Black",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/036-man.svg",
      name:"Martin",
      gender: "Man",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "White",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/037-man.svg",
      name:"Leo",
      gender: "Man",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "Yes",
      clothesColor: "Red",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/038-man.svg",
      name:"Manuel",
      gender: "Man",
      hairColor: "Blonde",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Black",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/039-man.svg",
      name:"Adel",
      gender: "Man",
      hairColor: "Black",
      moustache: "Yes",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Green",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/040-man.svg",
      name:"Adonis",
      gender: "Man",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Red",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/041-man.svg",
      name:"Ajaz",
      gender: "Man",
      hairColor: "Blonde",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Black",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/042-man.svg",
      name:"Akos",
      gender: "Man",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Red",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/043-woman.svg",
      name:"Josefa",
      gender: "Woman",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Black",
      skinColor: "Light",
      longHair: "Yes",
    },
    {
      img: "./assets/public/exercise-3/044-woman.svg",
      name:"Isabel",
      gender: "Woman",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "Pink",
      skinColor: "Light",
      longHair: "No",
    },
    {
      img: "./assets/public/exercise-3/045-woman.svg",
      name:"Cristina",
      gender: "Woman",
      hairColor: "Black",
      moustache: "No",
      glasses: "No",
      hatOrCap: "No",
      clothesColor: "White",
      skinColor: "Light",
      longHair: "No",
    },
  ];


}
